name: CI
on:
  push:
    branches: [ main ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3.7.0
        with: 
          node-version: 18.16.1
          
      - name: Instalação Mocha e dos pacotes para testes
        run: |
          cd src;
          npm install -g mocha;
          npm install
          
      - name: Execução do teste
        run: mocha src/test/convert.js
        
      - name: Construção da imagem Docker
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        uses: docker/build-push-action@v4.1.1
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            andrecoelhojr/aula-conversao-temperatura:v1
            andrecoelhojr/aula-conversao-temperatura:latest
