name: CI
on:
  push:
    branches: [ main ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3.7.0
        with: 
          node-version: 18.16.1
          
      - name: Instalação Mocha e dos pacotes para testes
        run: |
          cd src;
          npm install -g mocha;
          npm install
